# Methods

# Support Vector Machine-Binary

In [1]:
# Train & test
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df_train=pd.read_csv(r'C:\Users\ppulivarthi\AV_Hackthons\HR_Analytics\train_LZdllcl.csv')

In [2]:
print("******** No.of Row's and Column's in Dataframe********* \n ",df_train.shape,
     "\n \n **************Columns in Dataframe*********** \n ",df_train.columns,
     "\n \n **************Top 5 Row's in Dataframe *********** \n ",df_train.head())


******** No.of Row's and Column's in Dataframe********* 
  (54808, 14) 
 
 **************Columns in Dataframe*********** 
  Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met >80%', 'awards_won?',
       'avg_training_score', 'is_promoted'],
      dtype='object') 
 
 **************Top 5 Row's in Dataframe *********** 
     employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing             

In [3]:
df_train.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [4]:
df_train.age.unique()

array([35, 30, 34, 39, 45, 31, 33, 28, 32, 49, 37, 38, 41, 27, 29, 26, 24,
       57, 40, 42, 23, 59, 44, 50, 56, 20, 25, 47, 36, 46, 60, 43, 22, 54,
       58, 48, 53, 55, 51, 52, 21], dtype=int64)

In [5]:
df_train.drop(['employee_id'],axis=1,inplace=True)


In [6]:
df_train=df_train[:4000]

In [7]:
df_train.isna().sum()

department                0
region                    0
education               208
gender                    0
recruitment_channel       0
no_of_trainings           0
age                       0
previous_year_rating    305
length_of_service         0
KPIs_met >80%             0
awards_won?               0
avg_training_score        0
is_promoted               0
dtype: int64

In [8]:
#Creating Dummy variables for Categorical variables
df_train1=pd.get_dummies(df_train, columns = ['department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'previous_year_rating',
       'length_of_service'],drop_first=True)

In [9]:
X = df_train1.loc[:, df_train1.columns != 'is_promoted']
y = df_train1.loc[:, df_train1.columns == 'is_promoted']

In [ ]:
# seaborn.lmplot(*, x=None, y=None, data=None, hue=None, col=None, row=None, palette=None, col_wrap=None, height=5, aspect=1, markers='o', sharex=True, sharey=True, hue_order=None, col_order=None, row_order=None, legend=True, legend_out=True, x_estimator=None, x_bins=None, x_ci='ci', scatter=True, fit_reg=True, ci=95, n_boot=1000, units=None, seed=None, order=1, logistic=False, lowess=False, robust=False, logx=False, x_partial=None, y_partial=None, truncate=True, x_jitter=None, y_jitter=None, scatter_kws=None, line_kws=None, size=None)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.svm import SVC,LinearSVC

In [ ]:
# sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)

In [ ]:
# sklearn.svm.LinearSVC(penalty='l2', loss='squared_hinge', *, dual=True, tol=0.0001, C=1.0, multi_class='ovr', fit_intercept=True, intercept_scaling=1, class_weight=None, verbose=0, random_state=None, max_iter=1000)

In [12]:
#splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
# model=SVC(C=1, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)

In [13]:
model=LinearSVC(penalty='l2', loss='squared_hinge', dual=True, tol=0.0001, C=1, multi_class='ovr', fit_intercept=True, intercept_scaling=1, class_weight=None, verbose=0, random_state=None, max_iter=1000)

In [14]:
model.fit(X_train,y_train)

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1)

In [15]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
# y_pred = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

*********Accuracy_Score******
  0.9227272727272727

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.92      0.96      1300
           1       0.15      0.85      0.25        20

    accuracy                           0.92      1320
   macro avg       0.57      0.89      0.60      1320
weighted avg       0.98      0.92      0.95      1320


 **********Confusion Matrix********** 
 [[1201   99]
 [   3   17]]

**********f1 Score********* 
 0.24999999999999997


In [16]:
model=LinearSVC(penalty='l2', loss='squared_hinge', dual=True, tol=0.0001, C=0.4, multi_class='ovr', fit_intercept=True, intercept_scaling=1, class_weight=None, verbose=0, random_state=None, max_iter=1000)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
# y_pred = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


*********Accuracy_Score******
  0.9136363636363637

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.91      0.95      1318
           1       0.02      1.00      0.03         2

    accuracy                           0.91      1320
   macro avg       0.51      0.96      0.49      1320
weighted avg       1.00      0.91      0.95      1320


 **********Confusion Matrix********** 
 [[1204  114]
 [   0    2]]

**********f1 Score********* 
 0.03389830508474576


C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


# Method2

In [17]:
model=SVC(C=1, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)

In [18]:
model.fit(X_train,y_train)

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(C=1)

In [19]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
# y_pred = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

*********Accuracy_Score******
  0.9121212121212121

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.91      0.95      1320
           1       0.00      0.00      0.00         0

    accuracy                           0.91      1320
   macro avg       0.50      0.46      0.48      1320
weighted avg       1.00      0.91      0.95      1320


 **********Confusion Matrix********** 
 [[1204  116]
 [   0    0]]

**********f1 Score********* 
 0.0


C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

# Method-3

In [20]:
model=SVC(C=1, kernel='poly', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
# y_pred = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


*********Accuracy_Score******
  0.9121212121212121

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.91      0.95      1320
           1       0.00      0.00      0.00         0

    accuracy                           0.91      1320
   macro avg       0.50      0.46      0.48      1320
weighted avg       1.00      0.91      0.95      1320


 **********Confusion Matrix********** 
 [[1204  116]
 [   0    0]]

**********f1 Score********* 
 0.0


C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [23]:
model=SVC(C=1, kernel='sigmoid', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
y_pred = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


AttributeError: predict_proba is not available when  probability=False

In [22]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Method-4-probabilities

In [24]:
model=SVC(C=1, kernel='sigmoid', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=True, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


*********Accuracy_Score******
  0.9121212121212121

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.91      0.95      1320
           1       0.00      0.00      0.00         0

    accuracy                           0.91      1320
   macro avg       0.50      0.46      0.48      1320
weighted avg       1.00      0.91      0.95      1320


 **********Confusion Matrix********** 
 [[1204  116]
 [   0    0]]

**********f1 Score********* 
 0.0


C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [25]:
y_pred_prob

array([[0.97402082, 0.02597918],
       [0.89579673, 0.10420327],
       [0.95056549, 0.04943451],
       ...,
       [0.89666669, 0.10333331],
       [0.88088132, 0.11911868],
       [0.83410863, 0.16589137]])

In [26]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Method-5

In [ ]:
df_train1.columns

In [27]:
X = df_train1[['age','avg_training_score']]
y = df_train1.loc[:, df_train1.columns == 'is_promoted']

In [28]:
#splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
model=SVC(C=1, kernel='linear', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=True, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score
y_pred = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)
print("*********Accuracy_Score******\n ",accuracy_score(y_pred,y_test))
print("\n  Classification_Report****** \n",classification_report(y_pred,y_test))
print("\n **********Confusion Matrix********** \n",confusion_matrix(y_pred,y_test))
print("\n**********f1 Score********* \n",f1_score(y_pred,y_test))

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


*********Accuracy_Score******
  0.9121212121212121

  Classification_Report****** 
               precision    recall  f1-score   support

           0       1.00      0.91      0.95      1320
           1       0.00      0.00      0.00         0

    accuracy                           0.91      1320
   macro avg       0.50      0.46      0.48      1320
weighted avg       1.00      0.91      0.95      1320


 **********Confusion Matrix********** 
 [[1204  116]
 [   0    0]]

**********f1 Score********* 
 0.0


C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [29]:
y_pred_prob

array([[0.90669137, 0.09330863],
       [0.90671084, 0.09328916],
       [0.90671358, 0.09328642],
       ...,
       [0.90670584, 0.09329416],
       [0.90671348, 0.09328652],
       [0.90672424, 0.09327576]])

In [30]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# w=model.coef_[0]

In [ ]:
# a=-w[0]/w[1]
# xx=np.linspace(5,30)
# yy=a*xx-(model.intercept_[0])/w[1]
# b=model.support_vectors_[0]
# yy_down=a*xx+(b[1]-a*b[0])
# b=model.support_vectors_[1]
# yy_up=a*xx+(b[1]-a*b[0])

In [ ]:
# sns.lmplot('age','avg_training_score',data=df_train,hue='is_promoted',palette='Set1',fit_reg=False,scatter_kws={"s",70})
# plt.plot(xx,yy,linewidth=2,color='black')
# plt.plot(xx,yy_down,'K---')
# plt.plot(xx,yy_up,'K---')


# Nearest NeighborsClassifier

In [1]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

print(neigh.predict([[1.1]]))

print(neigh.predict_proba([[0.9]]))

[0]
[[0.66666667 0.33333333]]
