# Numpy

In [ ]:
#create array

In [1]:
import numpy as np

In [ ]:
# syntax:
# array(list,tuple,scalar,vector,matrix)

In [2]:
# scalar
scalar=np.array(3)

In [5]:
# scalar
print(scalar)

3


In [6]:
scalar_1=scalar*10

In [7]:
scalar_1

30

In [8]:
# Vector
vector=np.array([1,2,3,4])

In [10]:
# vector
print(vector)

[1 2 3 4]


In [11]:
vect=vector*10

In [12]:
vect

array([10, 20, 30, 40])

In [13]:
# matrix
matrix=np.array([[1,2,3],[4,5,6]])


In [14]:
matrix


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
matrix=np.array([[1,2,3],[4,5]])

C:\Users\ppulivarthi\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [16]:
matrix

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [17]:
matrix=np.array([[1,2,3],[4,5,np.nan]])

In [18]:
matrix

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [19]:
matrix=np.array([[1,2,3],[4,5,6],[9,8,7]])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [21]:
matrix=np.array([[[1,2,3],[4,5,6]],[[9,8,7],[11,12,13]]])

In [22]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9,  8,  7],
        [11, 12, 13]]])

In [ ]:
#Basic checks
# np.__version__
#ndim
#dtype
#shape
#reshape(rows,cols)
#reshape(-1)
#loops: for,np.nditer(arr)
# concatenate((arr1,arr2))
#stack,default axis=0,append rows
#hstack
#vstack
# dstack
#array_split(array,no_of_splits),axis
#where(condition)
# sort
#random.randint


In [23]:
print(np.__version__)

1.19.2


In [24]:
scalar=np.array(3)
print(scalar.ndim)

0

In [25]:
vector=np.array([1,2,3,4])

In [26]:
vector.ndim

1

In [27]:
matrix=np.array([[1,2,3],[4,5,6]])

In [28]:
matrix.ndim

2

In [29]:
matrix_ndim=np.array([[[1,2,3],[4,5,6]],[[9,8,7],[11,12,13]]])

In [30]:
matrix_ndim.ndim

3

In [32]:
matrix.dtype

dtype('int32')

In [33]:
vector_character=np.array(["a","b","c"])

In [35]:
vector_character.dtype

dtype('<U1')

In [36]:
vector_character.shape

(3,)

In [37]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
matrix.shape

(2, 3)

In [39]:
matrix_ndim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9,  8,  7],
        [11, 12, 13]]])

In [40]:
matrix_ndim.shape

(2, 2, 3)

In [41]:
#reshape(rows,cols)
vector_new=np.array([1,2,3,4,5,6,7,8])

In [42]:
vector_new

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
vect_reshape=vector_new.reshape(4,2) #4*2=8

In [44]:
vect_reshape

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
vect_reshape=vector_new.reshape(5,2)

ValueError: cannot reshape array of size 8 into shape (5,2)

In [46]:
vect_reshape=vector_new.reshape(2,4)

In [47]:
vect_reshape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
matrix.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#loops: for,np.nditer(arr)

In [52]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# vector
for p in vector:
    print(p)

1
2
3
4


In [53]:
for p in matrix:
    print(p)

[1 2 3]
[4 5 6]


In [54]:
for p in matrix:
    print(p)#[1 2 3]
    for x in p:
        print(x)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [55]:
# np.nditer(arr)
for i in np.nditer(matrix):
    print(i)

1
2
3
4
5
6


In [ ]:
# concatenate((arr1,arr2))

In [62]:
# arr1=np.array([1,2,3,4,5])
# arr2=np.array([10,11,12,13,14])

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[10,11],[12,13]])

In [66]:
arr1.shape

(2, 2)

In [63]:
concat_arr=np.concatenate((arr1,arr2))

In [64]:
concat_arr

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [67]:
concat_arr=np.concatenate((arr1,arr2),axis=0)

In [68]:
concat_arr

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [69]:
concat_arr=np.concatenate((arr1,arr2),axis=1)

In [70]:
concat_arr

array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

In [ ]:
#stack,default axis=0,append rows
#hstack
#vstack
# dstack

In [72]:
#array_split(array,no_of_splits),axis

arr1=np.array([1,2,3,4,5,6])

In [75]:
arr1=np.array([1,2,3,4,5])

In [76]:
arr_split=np.array_split(arr1,2)

In [77]:
arr_split

[array([1, 2, 3]), array([4, 5])]

In [79]:
#where(condition)
arr1=np.array([1,2,3,4,5])
eq_f=np.where(arr1==4)

In [81]:
print(eq_f)

(array([3], dtype=int64),)


In [82]:
eq_gr_f=np.where(arr1>=4)

In [83]:
eq_gr_f

(array([3, 4], dtype=int64),)

In [ ]:
#slicing-spliting the array
# positive slicing
# negative slicing

In [84]:
arr1=np.array([1,2,3,4,5,6])

In [85]:
type(arr1)

numpy.ndarray

In [86]:
arr1[0]

1

In [87]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [88]:
arr1[-3:]

array([4, 5, 6])

In [89]:
arr1[-1]

6